name: Build Container

on:
  push:
    tags:
    - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure Docker for multi-arch builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx for multi-arch builds
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, tag, and push docker image to the GitHub Container Registry
        run: make push

      - name: Update release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            CHANGELOG.md
          tag_name: "${{ github.ref_name }}"

      - run: |
          echo "Finished building and pushing containers for version ${{ github.ref_name }}."
