name: Linters and Tests

on:
  workflow_call:

jobs:
  pre-commit:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Run linter
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch

  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Run container tests
        run: |
          docker build .
